apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  type: NodePort
  ports:
    - name: queue
      port: 8161
      nodePort: 30011

    - name: endpoint
      port: 61616

curl -v http://10.106.46.127/ -H 'Host: fleetman.com'