apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: position-simulator
  template:
    metadata:
      labels:
        name: position-simulator
    spec:
      containers:
      - name: position-simulator
        image: richardchesterwood/k8s-fleetman-position-simulator:resources
        env: 
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
